export default {
  sign_in: 'Sign in with email',
  sign_up: 'Sign Up',
  auth_page_title: 'Hello',
  auth_page_text:
    'Welcome to the todo list! Where can you organize your daily tasks',
  sign_up_using: 'or sign up using',
  username: 'Username',
  password: 'Password',
  repeat_password: 'Repeat your password',
  email: 'Email',
  put_your_username: 'put your username here...',
  put_your_email: 'put your email here...',
  put_your_password: 'put your password here...',
  repeat_your_password: 'repeat your password here...',
  already_have_account: 'Already have a account?',
  cant_have_account: 'You can`t have a account?',
  return_to_login: 'Return to login page.',
  wrong_credentials_message: 'email and/or password are wrong',
  wrong_credentials_title: 'wrong credentials',
  uid: 'uid',
}
